# Site settings
title: Thiago Coelho
email: thiagoamc@gmail.com
description: > # thiagomc
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://thiagoamc.github.io/" # the base hostname & protocol for your site
twitter_username: thiagoamc
github_username:  thiagoamc

# Build settings
markdown: kramdown
